baseurl = "https://mini.ying-ish.com/"
languageCode = "en-us"
title = "mini-ying"
copyright = "This work is licensed under a Creative Commons Attribution-Non-Commercial ShareAlike 4.0 International License."

# Add your tracking code to enable Google Analytics
googleAnalytics = "UA-137829607-1"


# Posts per page
paginate = 20


[Params]
	opengraph = true
	imgurl = "https://s3.us-east-2.amazonaws.com/ying-ish/miniposts/"
	tiny = "https://song.link/i/"
[Author]
	name = "mini-ying"
	username = "ying"